// Realistic mock data for demo mode — no Supabase needed

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@tenderwatch.dk',
}

export const DEMO_COMPANY = {
  id: 'demo-company-001',
  user_id: DEMO_USER.id,
  name: 'Nordic Maritime Engineering ApS',
  industry: 'Maritime Engineering',
  country_code: 'DK',
  created_at: '2026-03-01T00:00:00Z',
}

export const DEMO_SUBSCRIPTION = {
  id: 'demo-sub-001',
  user_id: DEMO_USER.id,
  stripe_customer_id: null,
  stripe_subscription_id: null,
  plan: 'professional' as const,
  status: 'active' as const,
  current_period_end: '2026-05-01T00:00:00Z',
  created_at: '2026-03-01T00:00:00Z',
  updated_at: '2026-03-01T00:00:00Z',
}

export const DEMO_PROFILES = [
  {
    id: 'demo-profile-001',
    user_id: DEMO_USER.id,
    name: 'Maritime & Naval',
    cpv_codes: ['71300000', '71327000', '34500000', '34510000', '50240000'],
    keywords: ['maritime', 'naval', 'ship design', 'hull', 'vessel'],
    exclude_keywords: ['cleaning', 'catering'],
    countries: ['DK', 'NO', 'SE', 'DE'],
    min_value_eur: 100000,
    max_value_eur: null,
    procedure_types: [],
    active: true,
    notify_email: true,
    notify_push: false,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'demo-profile-002',
    user_id: DEMO_USER.id,
    name: 'Structural Engineering',
    cpv_codes: ['71312000', '71327000', '71240000'],
    keywords: ['structural analysis', 'load-bearing', 'FEM'],
    exclude_keywords: [],
    countries: ['DK', 'NO'],
    min_value_eur: null,
    max_value_eur: null,
    procedure_types: [],
    active: true,
    notify_email: true,
    notify_push: false,
    created_at: '2026-03-10T00:00:00Z',
    updated_at: '2026-03-10T00:00:00Z',
  },
]

export const DEMO_TENDERS = [
  {
    id: 'demo-tender-001',
    source: 'ted' as const,
    external_id: '2026/S 085-123456',
    title: 'Ship Hull Structural Analysis Services',
    description: 'The Danish Defence Acquisition and Logistics Organisation (DALO) is seeking qualified engineering consultancies to provide structural analysis and design verification services for naval vessel hull structures. The framework agreement covers structural integrity assessments, fatigue analysis, and design optimization for existing and new naval platforms. The contractor will work closely with DALO engineers and shipyard partners. Services include finite element analysis (FEA), classification society liaison, and documentation per NATO STANAG requirements.',
    buyer_name: 'Danish Defence Acquisition and Logistics Organisation',
    buyer_country: 'DK',
    cpv_codes: ['71327000', '71300000', '34515000'],
    procedure_type: 'Open',
    tender_type: 'Contract notice',
    estimated_value_eur: 2500000,
    currency: 'EUR',
    submission_deadline: '2026-05-15T14:00:00Z',
    publication_date: '2026-04-02',
    document_url: null,
    ted_url: 'https://ted.europa.eu/en/notice/-/2026-S-085-123456',
    language: 'EN',
    ai_summary: '- WHAT: Structural analysis and design verification services for Danish naval vessel hull structures, including FEA and fatigue analysis.\n- WHO: Danish Defence (DALO) — a recurring procurer of naval engineering services with established shipyard partnerships.\n- VALUE: EUR 2.5M framework agreement over 4 years.\n- REQUIREMENTS:\n  • NATO security clearance required\n  • Minimum 5 years experience in naval structural engineering\n  • ISO 9001 certification\n- DEADLINE: 15 May 2026, 14:00 CET\n- FIT FOR SME: Challenging due to security clearance but framework allows sub-contracting opportunities.',
    ai_summary_generated_at: '2026-04-03T10:00:00Z',
    raw_data: null,
    created_at: '2026-04-02T06:30:00Z',
  },
  {
    id: 'demo-tender-002',
    source: 'ted' as const,
    external_id: '2026/S 086-234567',
    title: 'Naval Vessel Design Consultancy — Corvette Class',
    description: 'The Norwegian Defence Materiel Agency invites tenders for design consultancy services related to the next-generation corvette program. Scope includes concept design, hydrodynamic optimization, and preliminary structural design. The agency requires experience with military vessel design to NATO standards.',
    buyer_name: 'Norwegian Defence Materiel Agency',
    buyer_country: 'NO',
    cpv_codes: ['71300000', '34513300', '71310000'],
    procedure_type: 'Restricted',
    tender_type: 'Contract notice',
    estimated_value_eur: 4100000,
    currency: 'EUR',
    submission_deadline: '2026-05-22T12:00:00Z',
    publication_date: '2026-04-01',
    document_url: null,
    ted_url: 'https://ted.europa.eu/en/notice/-/2026-S-086-234567',
    language: 'EN',
    ai_summary: null,
    ai_summary_generated_at: null,
    raw_data: null,
    created_at: '2026-04-01T06:30:00Z',
  },
  {
    id: 'demo-tender-003',
    source: 'ted' as const,
    external_id: '2026/S 087-345678',
    title: 'Port Infrastructure Structural Engineering — Nordhavn Expansion',
    description: 'Municipality of Copenhagen seeks structural engineering consultancy for the Nordhavn port expansion project, phase 3. Work includes quay wall design, foundation analysis, and construction supervision.',
    buyer_name: 'Municipality of Copenhagen',
    buyer_country: 'DK',
    cpv_codes: ['71312000', '71322000', '45241000'],
    procedure_type: 'Open',
    tender_type: 'Contract notice',
    estimated_value_eur: 1800000,
    currency: 'EUR',
    submission_deadline: '2026-05-30T23:59:00Z',
    publication_date: '2026-04-03',
    document_url: null,
    ted_url: 'https://ted.europa.eu/en/notice/-/2026-S-087-345678',
    language: 'EN',
    ai_summary: null,
    ai_summary_generated_at: null,
    raw_data: null,
    created_at: '2026-04-03T06:30:00Z',
  },
  {
    id: 'demo-tender-004',
    source: 'ted' as const,
    external_id: '2026/S 088-456789',
    title: 'Ship Repair and Maintenance Services — Royal Danish Navy',
    description: 'Framework agreement for ongoing repair and maintenance of Royal Danish Navy vessels, including hull maintenance, propulsion system overhaul, and emergency dry-docking. Multiple lots available.',
    buyer_name: 'Danish Defence — Naval Command',
    buyer_country: 'DK',
    cpv_codes: ['50240000', '50241000', '34510000'],
    procedure_type: 'Open',
    tender_type: 'Contract notice',
    estimated_value_eur: 8500000,
    currency: 'EUR',
    submission_deadline: '2026-06-10T14:00:00Z',
    publication_date: '2026-04-04',
    document_url: null,
    ted_url: 'https://ted.europa.eu/en/notice/-/2026-S-088-456789',
    language: 'EN',
    ai_summary: null,
    ai_summary_generated_at: null,
    raw_data: null,
    created_at: '2026-04-04T06:30:00Z',
  },
  {
    id: 'demo-tender-005',
    source: 'ted' as const,
    external_id: '2026/S 089-567890',
    title: 'Maritime Safety Equipment Inspection Services',
    description: 'Swedish Transport Agency procurement for inspection and certification services for maritime safety equipment across Swedish commercial ports.',
    buyer_name: 'Swedish Transport Agency',
    buyer_country: 'SE',
    cpv_codes: ['71300000', '63720000'],
    procedure_type: 'Open',
    tender_type: 'Contract notice',
    estimated_value_eur: 650000,
    currency: 'EUR',
    submission_deadline: '2026-05-20T12:00:00Z',
    publication_date: '2026-04-01',
    document_url: null,
    ted_url: 'https://ted.europa.eu/en/notice/-/2026-S-089-567890',
    language: 'EN',
    ai_summary: null,
    ai_summary_generated_at: null,
    raw_data: null,
    created_at: '2026-04-01T06:30:00Z',
  },
  {
    id: 'demo-tender-006',
    source: 'ted' as const,
    external_id: '2026/S 090-678901',
    title: 'Offshore Wind Farm Foundation Design — Kriegers Flak II',
    description: 'Energinet seeks engineering consultancy for the structural design of monopile and jacket foundations for the Kriegers Flak II offshore wind farm. Includes geotechnical assessment, wave load analysis, and fatigue life prediction.',
    buyer_name: 'Energinet',
    buyer_country: 'DK',
    cpv_codes: ['71312000', '71327000', '45262000'],
    procedure_type: 'Negotiated',
    tender_type: 'Contract notice',
    estimated_value_eur: 3200000,
    currency: 'EUR',
    submission_deadline: '2026-06-01T14:00:00Z',
    publication_date: '2026-04-04',
    document_url: null,
    ted_url: 'https://ted.europa.eu/en/notice/-/2026-S-090-678901',
    language: 'EN',
    ai_summary: null,
    ai_summary_generated_at: null,
    raw_data: null,
    created_at: '2026-04-04T06:30:00Z',
  },
  {
    id: 'demo-tender-007',
    source: 'mitudbud' as const,
    external_id: 'MU-2026-04-1234',
    title: 'Havneingeniør — Rådgivning vedr. kajanlæg i Esbjerg',
    description: 'Esbjerg Kommune søger rådgivende ingeniørvirksomhed til strukturel vurdering og redesign af kajanlæg i Esbjerg Havn.',
    buyer_name: 'Esbjerg Kommune',
    buyer_country: 'DK',
    cpv_codes: ['71312000', '71300000'],
    procedure_type: 'Open',
    tender_type: 'Contract notice',
    estimated_value_eur: 450000,
    currency: 'DKK',
    submission_deadline: '2026-05-10T12:00:00Z',
    publication_date: '2026-04-03',
    document_url: null,
    ted_url: null,
    language: 'DA',
    ai_summary: null,
    ai_summary_generated_at: null,
    raw_data: null,
    created_at: '2026-04-03T07:00:00Z',
  },
]

export const DEMO_MATCHES = [
  {
    id: 'demo-match-001',
    tender_id: 'demo-tender-001',
    profile_id: 'demo-profile-001',
    user_id: DEMO_USER.id,
    relevance_score: 92,
    matched_cpv: ['71327000', '71300000'],
    matched_keywords: ['naval', 'hull'],
    ai_reason: 'Directly relevant — structural analysis for naval vessel hulls matches maritime engineering profile',
    notified: true,
    notified_at: '2026-04-03T07:30:00Z',
    seen: false,
    bookmarked: true,
    created_at: '2026-04-03T07:00:00Z',
  },
  {
    id: 'demo-match-002',
    tender_id: 'demo-tender-002',
    profile_id: 'demo-profile-001',
    user_id: DEMO_USER.id,
    relevance_score: 87,
    matched_cpv: ['71300000'],
    matched_keywords: ['naval', 'vessel'],
    ai_reason: 'Corvette-class vessel design consultancy aligns with naval engineering expertise',
    notified: true,
    notified_at: '2026-04-03T07:30:00Z',
    seen: false,
    bookmarked: false,
    created_at: '2026-04-02T07:00:00Z',
  },
  {
    id: 'demo-match-003',
    tender_id: 'demo-tender-003',
    profile_id: 'demo-profile-002',
    user_id: DEMO_USER.id,
    relevance_score: 65,
    matched_cpv: ['71312000'],
    matched_keywords: ['structural analysis'],
    ai_reason: 'Offshore wind foundation design requires structural engineering expertise',
    notified: true,
    notified_at: '2026-04-04T07:30:00Z',
    seen: true,
    bookmarked: false,
    created_at: '2026-04-04T07:00:00Z',
  },
  {
    id: 'demo-match-004',
    tender_id: 'demo-tender-004',
    profile_id: 'demo-profile-001',
    user_id: DEMO_USER.id,
    relevance_score: 78,
    matched_cpv: ['50240000', '34510000'],
    matched_keywords: ['ship', 'vessel'],
    ai_reason: 'Ship repair and maintenance services for the Royal Danish Navy',
    notified: false,
    notified_at: null,
    seen: false,
    bookmarked: false,
    created_at: '2026-04-04T07:00:00Z',
  },
  {
    id: 'demo-match-005',
    tender_id: 'demo-tender-005',
    profile_id: 'demo-profile-001',
    user_id: DEMO_USER.id,
    relevance_score: 45,
    matched_cpv: ['71300000'],
    matched_keywords: ['maritime'],
    ai_reason: 'Maritime safety equipment inspection — tangentially related to maritime sector',
    notified: false,
    notified_at: null,
    seen: false,
    bookmarked: false,
    created_at: '2026-04-02T07:00:00Z',
  },
  {
    id: 'demo-match-006',
    tender_id: 'demo-tender-006',
    profile_id: 'demo-profile-002',
    user_id: DEMO_USER.id,
    relevance_score: 72,
    matched_cpv: ['71312000', '71327000'],
    matched_keywords: [],
    ai_reason: 'Port infrastructure structural engineering matches civil/structural profile',
    notified: false,
    notified_at: null,
    seen: false,
    bookmarked: true,
    created_at: '2026-04-04T07:00:00Z',
  },
  {
    id: 'demo-match-007',
    tender_id: 'demo-tender-007',
    profile_id: 'demo-profile-002',
    user_id: DEMO_USER.id,
    relevance_score: 58,
    matched_cpv: ['71312000', '71300000'],
    matched_keywords: [],
    ai_reason: 'Harbour engineering consultancy relevant to structural engineering profile',
    notified: false,
    notified_at: null,
    seen: false,
    bookmarked: false,
    created_at: '2026-04-03T07:00:00Z',
  },
]

// Helper to get joined match+tender data (mimics Supabase join)
export function getDemoMatchesWithTenders() {
  return DEMO_MATCHES
    .map(m => ({
      ...m,
      tender: DEMO_TENDERS.find(t => t.id === m.tender_id)!,
    }))
    .sort((a, b) => b.relevance_score - a.relevance_score)
}
